name: 'Setup Emacs dev build'
description: 'Setup a development build of Emacs'

inputs:
  repository:
    description: >
      Emacs repository name with owner, for example: octocat/emacs.
    default: '${{ github.repository_owner }}/emacs'

  path:
    description: >
      The value of relative path under ${GITHUB_WORKSPACE} where to check out
      Emacs source code and perform build.
    default: emacs

  base-ref:
    description: >
      Use this branch, tag, or SHA to perform base Emacs build.
    default: master

  dev-ref:
    description: >
      Use this branch, tag, or SHA to perform development Emacs build.

  tmate:
    description: >
      When true, run the action with tmate debugging enabled
      (https://github.com/marketplace/actions/debugging-with-tmate)
    default: false

  configure-arguments:
    description: >
      Arguments to pass to configure script.
    default: >-
      --without-native-compilation
      --with-gnutls
      --with-modules

  cache:
    description: >
      When true, cache the base Emacs build.  Enabling cache should speed up
      rebuilds on dev-ref.
    default: true

  linux-extra-packages:
    description: >
      Extra packages to install on top of linux-packages on a Linux runner.
    default: ''

  macos-extra-packages:
    description: >
      Extra packages to install on top of macos-packages on a macOS runner.
    default: ''

  windows-extra-packages:
    description: >
      Extra packages to install on top of windows-packages on a Windows runner.
    default: ''

  linux-packages:
    description: >
      Packages to install with apt-get on a Linux runner.
    default: >-
      autoconf
      automake
      build-essential
      libgif-dev
      libgnutls28-dev
      libgmp-dev
      libgtk-3-dev
      libharfbuzz-dev
      libjpeg-dev
      libncurses-dev
      libpng-dev
      libsqlite3-dev
      libtiff-dev
      libtree-sitter-dev
      libwebp-dev
      libxpm-dev
      texinfo
      tree-sitter-cli

  macos-packages:
    description: >
      Packages to install with Homebrew on a macOS runner.
    default: >-
      autoconf
      automake
      awk
      coreutils
      giflib
      gcc
      gmp
      gnu-sed
      gnu-tar
      gnutls
      libjpeg
      libpng
      librsvg
      libtiff
      libxml2
      libxpm
      m4
      make
      pkg-config
      sqlite
      texinfo
      tree-sitter
      webp
      zlib
      xz

  windows-packages:
    description: >
      Packages to install with MSYS2/pacman on a Windows runner.
    default: >-
      base-devel
      autoconf
      automake
      git
      texinfo
      make
      mingw-w64-x86_64-giflib
      mingw-w64-x86_64-gnutls
      mingw-w64-x86_64-gmp
      mingw-w64-x86_64-harfbuzz
      mingw-w64-x86_64-libjpeg-turbo
      mingw-w64-x86_64-libpng
      mingw-w64-x86_64-librsvg
      mingw-w64-x86_64-libtiff
      mingw-w64-x86_64-libtree-sitter
      mingw-w64-x86_64-libwebp
      mingw-w64-x86_64-libxml2
      mingw-w64-x86_64-xpm-nox
      mingw-w64-x86_64-make
      mingw-w64-x86_64-sqlite3
      mingw-w64-x86_64-texinfo
      mingw-w64-x86_64-toolchain
      mingw-w64-x86_64-tree-sitter
      mingw-w64-x86_64-zlib

outputs:
  path:
    description: >
      The path used to build Emacs.
    value: ${{ inputs.path }}

  repository:
    description: >
      Name of the repository used to build Emacs.
    value: ${{ inputs.repository }}

  ref:
    description: >
      The branch, tag, or SHA used to build Emacs.
    value: >-
      ${{ inputs.dev-ref != ''
          && steps.checkout-dev-branch.outputs.ref
          || ( inputs.cache
               && steps.checkout-base-branch.outputs.ref
               || inputs.base-ref ) }}

  cache-key:
    description: >
      The key used to cache base Emacs build.
    value: >-
      ${{ runner.os == 'Windows'
          && steps.cache-key-windows.outputs.key
          || steps.cache-key-linux-macos.outputs.key }}

  cache-hit:
    description: >
      True when cache hit.
    value: ${{ steps.cache-cask-packages.outputs.cache-hit }}

  msys2-location:
    description: >
      The absolute path of the MSYS2 installation location.
    value: ${{ steps.setup-msys2.outputs.msys2-location }}

runs:
  using: 'composite'
  steps:
    - name: Install dependencies on Linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y                 \
            ${{ inputs.linux-packages }}        \
            ${{ inputs.linux-extra-packages }}

    - name: Install dependencies on macOS
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        brew update
        brew install                            \
            ${{ inputs.macos-packages }}        \
            ${{ inputs.macos-extra-packages }}

    - name: Setup MSYS2 and install dependencies on Windows
      id: setup-msys2
      if: ${{ runner.os == 'Windows' }}
      uses: msys2/setup-msys2@v2
      with:
        release: false
        install: >-
          ${{ inputs.windows-packages }}
          ${{ inputs.windows-extra-packages }}

    - name: Configure git (pwsh/bash)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        & ${{ github.action_path }}\configure-git.ps1 `
           -MSYS2Location ${{ steps.setup-msys2.outputs.msys2-location }}

    - name: Configure git (msys2)
      if: ${{ runner.os == 'Windows' }}
      shell: msys2 {0}
      run: |
        '${{ github.action_path }}\configure-git.sh' msys2

    - name: Configure git
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: |
        ${{ github.action_path }}/configure-git.sh

    - name: Get Emacs cache key on Windows
      if: >-
        ${{ runner.os == 'Windows'
            && inputs.cache == 'true' }}
      id: cache-key-windows
      shell: msys2 {0}
      run: |
        echo "key=$('${{ github.action_path }}\get-cache-key.sh'    \
                        ${{ runner.os }}                            \
                        ${{ github.server_url }}                    \
                        ${{ inputs.repository }}                    \
                        ${{ inputs.base-ref }}                      \
                        "${{ inputs.configure-arguments }}"         \
                        "${{ inputs.windows-packages }}"            \
                        "${{ inputs.windows-extra-packages }}")"    \
            >> "$GITHUB_OUTPUT"

    - name: Get Emacs cache key on Linux/macOS
      if: >-
        ${{ runner.os != 'Windows'
            && inputs.cache == 'true' }}
      id: cache-key-linux-macos
      shell: bash
      run: |
        echo "key=$(${{ github.action_path}}/get-cache-key.sh       \
                        ${{ runner.os }}                            \
                        ${{ github.server_url }}                    \
                        ${{ inputs.repository }}                    \
                        ${{ inputs.base-ref }}                      \
                        "${{ inputs.configure-arguments }}"         \
                        "${{ runner.os == 'Linux'
                             && inputs.linux-packages
                             || inputs.macos-packages }}"           \
                        "${{ runner.os == 'Linux'
                             && inputs.linux-extra-packages
                             || inputs.macos-extra-packages }}")"   \
            >> "$GITHUB_OUTPUT"

    - name: Restore cached Emacs build on base branch
      if: ${{ inputs.cache == 'true' }}
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.path }}
        key: >
          ${{ runner.os == 'Windows'
              && steps.cache-key-windows.outputs.key
              || steps.cache-key-linux-macos.outputs.key }}

    - name: Checkout Emacs source on base branch
      id: checkout-base-branch
      if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.base-ref }}
        path: ${{ inputs.path }}

    - name: Configure and build Emacs on base branch on Windows
      if: >-
        ${{ runner.os == 'Windows'
            && steps.restore-cache.outputs.cache-hit != 'true' }}
      shell: msys2 {0}
      working-directory: ${{ inputs.path }}
      run: |
        '${{ github.action_path}}\configure-build-emacs.sh' \
            "${{ inputs.configure-arguments }}"

    - name: Configure and build  Emacs on base branch on Linux/macOS
      if: >-
        ${{ runner.os != 'Windows'
            && steps.restore-cache.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        ${{ github.action_path}}/configure-build-emacs.sh \
            "${{ inputs.configure-arguments }}"

    - name: Cache Emcas build on master branch
      if: >-
        ${{ inputs.cache == 'true'
            && steps.restore-cache.outputs.cache-hit != 'true'}}
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.path }}
        key: >
          ${{ runner.os == 'Windows'
              && steps.cache-key-windows.outputs.key
              || steps.cache-key-linux-macos.outputs.key }}

    - name: Checkout Emacs source on dev branch
      id: checkout-dev-branch
      if: ${{ inputs.dev-ref != '' }}
      uses: actions/checkout@v4
      with:
        clean: false
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.dev-ref }}
        path: ${{ inputs.path }}

    - name: Build Emacs source on dev branch on Windows
      if: >-
        ${{ runner.os == 'Windows'
            && inputs.dev-ref != '' }}
      shell: msys2 {0}
      working-directory: ${{ inputs.path }}
      run: |
        '${{ github.action_path}}\build-emacs.sh'

    - name: Build Emacs source on dev branch on Linux/macOS
      if: >-
        ${{ runner.os != 'Windows'
            && inputs.dev-ref != '' }}
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        ${{ github.action_path}}/build-emacs.sh

    - name: Setup shell wrapper on Windows
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        & ${{ github.action_path }}\setup-shell-wrapper.ps1

    - name: Setup custom shell on Linux/macOS
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: |
        ${{ github.action_path }}/setup-shell-wrapper.sh

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: >-
        ${{ always()
            && inputs.tmate == 'true' }}
      with:
        msys2-location: ${{ steps.setup-msys2.outputs.msys2-location }}
        detached: true
