#+title: setup-emacs-dev — GitHub Action for Building Emacs from Source
#+author: Przemysław Kryger
#+language: en
#+startup: showeverything
#+startup: literallinks
#+options: toc:nil num:nil author:nil

** Overview
:properties:
:custom_id: overview
:end:
The =setup-emacs-dev= action provides a simple facility for obtaining a freshly
built copy of Emacs directly from a user-selected branch of a user-selected
Emacs repository.  Its purpose is narrowly defined: it builds Emacs, and does
not attempt to install, package, or configure the resulting binaries for use in
a typical package testing CI workflow.

This action may be useful for users wishing to confirm build-ability and
test-ability of their development branches.  For example for running tests
during development of patches for Emacs source code.  The action functions on
all GitHub-hosted runners: GNU/Linux, Microsoft Windows, and macOS.  See
[[#comparison-with=other-emacs-setup-actions][below]] for comparison with other
GitHub actions.

** Branch Selection
:properties:
:custom_id: branch-selection
:end:
Two kinds of branches may be specified:
- Base branch — typically =master= (which is the default) or any other branch,
  tag, or SHA, see input ~base-ref~.
- Development branch — a branch, tag, or SHA containing work-in-progress
  modifications or experimental code, see input ~dev-ref~.
The action will check out the selected base branch and proceed to build Emacs
using the system’s native build tools and cache the result (unless opted out,
see [[#action-inputs-and-outputs-reference][Inputs and Outputs Reference]]).
After building a base branch (or restoring a previous build from cache) the
action checks out development branch and performs a build on it.

** Basic Usage
:properties:
:custom_id: basic-usage
:end:
The following example demonstrates a minimal configuration using the
=setup-emacs-dev= action to build Emacs from a =dev-branch= branch that has
been spoon off the =master= branch, in the workflow owner's =emacs= repository
fork on GitHub.

#+begin_src yaml
name: Build Emacs
on:
  push:
  pull_request:
jobs:
  build-emacs:
    runs-on: ubuntu-latest
  steps:
    - name: Build Emacs from dev-branch
      id: build-emacs-dev-branch
      uses: pkryger/setup-emacs-dev@main
      with:
        dev-ref: dev-branch
#+end_src
The build artifacts will be available in the ~${{
steps.build-emacs-dev-branch.outputs.path }}~ which is relative path to
workflow’s workspace directory. Please note that no installation step is
performed, i.e., the action doesn't call ~make install~.

N.B. By default Build Emacs _without_ native compilation.  Call the action with
custom ~configure-arguments~ to enable native compilation.

** Run Tests on a Development Branch
:properties:
:custom_id: run-tests-on-a-development-branch
:end:
It is possible to run tests on a development branch.  The following example
demonstrates how to achieve that on all supported systems on GitHub.

#+begin_src yaml
name: Run tests
on:
  push:
  pull_request:
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Setup Emacs dev build
        id: setup-emacs-dev
        uses: pkryger/emacs-dev@main
        with:
          dev-ref: dev-branch
      - name: Run tests
        shell: setup-emacs-dev-bash {0}
        working-directory: ${{ steps.setup-emacs-dev.outputs.path }}
        run: |
          ./src/emacs -batch \
              -l path/to/my-tests-file.el \
              -f ert-run-tests-batch-and-exit
#+end_src

N.B. This action uses a ~setup-emacs-dev-bash~ as a ~shell~ argument.  This is
a wrapper installed by this action that provides a single named entry point for
a ~bash~ shell.  While it is possible to specify ~bash~ as a ~shell~ argument
in a user workflow step, that, on a Windows runner, will use bash shell
included with Git for Windows (see
[[https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#defaultsrunshell][reference]]).
In such a case _no_ MSYS2 MinGW installed programs are available in ~PATH~.  In
contrast, with ~setup-emacs-dev-bash~ the step execution occurs within MSYS2
provided ~bash~ shell, with all MSYS2 MinGW installed programs available.
** Build a Debug Emacs Executable
This action supports passing arbitrary arguments to ~configure~ script.  It
includes passing environment variables, which can be used to produce a debug
Emacs executable.

In addition, GDB on Linux and Windows as well as LLVM on macOS are setup, such
that Emacs GDB/LLDB configuration is automatically applied.

#+begin_src yaml
name: Debug Emacs
on:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Setup Emacs debug build
        uses: pkryger/emacs-dev@main
        with:
          configure-arguments: >-
            --without-native-compilation
            --with-modules
            --with-gnutls
            CFLAGS='-O0 -g3'
          tmate: true
#+end_src

This will spun a three
[tmate](https://github.com/marketplace/actions/debugging-with-tmate) sessions,
see build log for connection string.

Once connected, to a =tmate= session, user can:
#+begin_src shell
$ emacs/src/emacs -nw # start emacs
#+end_src
Type =C-b c= to create a new tmux window.  Then in the new window type:
#+begin_src shell
$ ps # to get the Emacs's process PID
$ cd emacs/src
$ gdb emacs # or 'lldb emacs' on macOS
(gdb) attach <PID>
#+end_src
And use =C-b n=/=C-b p= to switch between =tmux= windows with GDB/LLDB and
Emacs.

** Action Inputs and Outputs Reference
:properties:
:custom_id: action-inputs-and-outputs-reference
:end:
#+begin_src yaml
inputs:
  repository:
    description: >
      Emacs repository name with owner, for example: octocat/emacs.
    default: '${{ github.repository_owner }}/emacs'

  path:
    description: >
      The value of relative path under ${GITHUB_WORKSPACE} where to check out
      Emacs source code and perform build.
    default: emacs

  base-ref:
    description: >
      Use this branch, tag, or SHA to perform base Emacs build.
    default: master

  dev-ref:
    description: >
      Use this branch, tag, or SHA to perform development Emacs build.

  tmate:
    description: >
      Run the action with tmate debugging enabled
      (https://github.com/marketplace/actions/debugging-with-tmate)
    default: false

  configure-arguments:
    description: >
      Arguments to pass to configure script, one argument per line.
    default: |-
      --without-native-compilation
      --with-gnutls
      --with-modules

  cache:
    description: >
      Cache the base Emacs build.  Enabling cache should speed up rebuilds on
      dev-ref.
    default: true

  upgrade:
    description: >
      Upgrade packages installed in runner.  This issues 'apt-get upgrade' (on
      Linux), 'brew upgrade' (on macOS), and 'pacman --sysupgrade' (on Windows)
      before installing packages.
    default: false

  linux-extra-packages:
    description: >
      Extra packages to install on top of linux-packages on a Linux runner.
    default: ''

  macos-extra-packages:
    description: >
      Extra packages to install on top of macos-packages on a macOS runner.
    default: ''

  windows-extra-packages:
    description: >
      Extra packages to install on top of windows-packages on a Windows runner.
    default: ''

  linux-packages:
    description: >
      Packages to install with apt-get on a Linux runner.
    default: >-
      # see action.yml

  macos-packages:
    description: >
      Packages to install with Homebrew on a macOS runner.
    default: >-
      # see action.yml

  windows-packages:
    description: >
      Packages to install with MSYS2/pacman on a Windows runner.
    default: >-
      # see action.yml

outputs:
  path:
    description: >
      The path used to build Emacs.

  repository:
    description: >
      Name of the repository used to build Emacs.

  ref:
    description: >
      The branch, tag, or SHA used to build Emacs.

  cache-key:
    description: >
      The key used to cache base Emacs build.

  cache-hit:
    description: >
      True when cache hit.

  msys2-location:
    description: >
      The absolute path of the MSYS2 installation location.
#+end_src

** Comparison with Other Emacs Setup Actions
:properties:
:custom_id: comparison-with=other-emacs-setup-actions
:end:
Users wishing to test packages or configure Emacs for use within their
workflows should note that this action does not install Emacs on the
runner.  For these more common use cases the following actions may be
more suitable:
- Purcell’s [[https://github.com/purcell/setup-emacs][setup-emacs]]
- jcs090218’s [[https://github.com/jcs090218/setup-emacs][setup-emacs]]
- kiennq’s [[https://github.com/kiennq/emacs-build][emacs-build]]
These actions provide ready-to-use Emacs installations tailored for
package testing and CI usage.

** Feedback and Contributions
:properties:
:custom_id: feedback-and-contributions
:end:
Users are encouraged to report issues or propose improvements via the
project’s GitHub issue tracker. Contributions are welcome.

** License
:properties:
:custom_id: license
:end:
This package is licensed under the [[https://www.gnu.org/licenses/gpl-3.0.en.html][GPLv3 License]].

# LocalWords: SHA
