name: Debug Emacs

on:
  workflow_dispatch:

jobs:

  debug-emacs-31-0-90-release:
    runs-on: windows-2025
    steps:
      - uses: pkryger/setup-emacs-dev@dev
        with:
          tmate: true


  debug-emacs-31-0-90-runner:
    runs-on: windows-2025
    steps:
      - uses: pkryger/setup-emacs-dev@dev

      - uses: mxschmitt/action-tmate@v3
